### ISSUE TITLE
Run the code?

### ISSUE THREAD

**Issue by dtokkk** [0XDE57/scales#1]
How can I run the code? Thanks

**Comment by 0xDE57** [comment]
oh, I suppose I forgot to add instructions...

1. install python 3.
2. install python-rtmidi library from pip:
`pip install python-rtmidi`
3. run:
`python scales.py`


let me know if you need further direction.

**Comment by 0xDE57** [comment]
added build and run instructions to readme. 

feel free to reopen if you run into issues.
